apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80          # ClusterIP port
      targetPort: 5000  # Must match containerPort
  type: ClusterIP
