apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
  namespace: dev-team
spec:
  containers:
    - name: stress-container
      image: polinux/stress
      command: ["stress"]
      args: ["--cpu", "1", "--timeout", "600"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
