apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: main-app
      image: busybox
      command: ['sh', '-c', 'while true; do echo Main container running; sleep 5; done']

    - name: sidecar
      image: busybox
      command: ['sh', '-c', 'while true; do echo Sidecar logging...; sleep 5; done']
