name: CI/CD to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-k8s-app:latest ./Day13/app
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-k8s-app:latest

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Deploy to Kubernetes
      run: echo "Skipping deployment because runner is not connected to local cluster"

